[FEAT]: Cell 커스텀, Log 추가 -> [MERGE]: feature/stopwatch-page -> main
KangJiHun1028/StopWatch pull request #10
Opened 2023-10-22 06:35 UTC by KangJiHun1028

Cell 파일 수정하여 커스텀 Cell 제작 및 Label을 띄워 Log 구현

2023-10-23 05:27 UTC, JongHoon023 requested changes
추가적으로 중복 코드가 많이 보이므로 중복 코드를 없애는 구조로 코드를 작성해야 함.

2023-10-23 05:27 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
여러 번 사용되며 변하지 않는 값일 경우 상수로 정의 필요.

2023-10-23 05:27 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
96번 줄과 중복.

2023-10-23 05:27 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
96번 줄과 중복.

2023-10-23 05:27 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
96번 줄과 중복

2023-11-10 08:24 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
상수로 따로 뺌.

2023-11-15 05:58 UTC, JongHoon023 requested changes
중복 코드를 제거하는데 집중하면 좋음

2023-11-15 05:58 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        addLog(status: currentStatus, title: currentTime, date: currentDateString)
142 줄과 같은 중복 코드 제거 방법을 고민해볼 필요가 있음.

2023-11-15 05:58 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        addLog(status: currentStatus, title: currentTime, date: currentDateString)
128 줄과 같은 중복 코드 제거 방법을 고민해볼 필요가 있음.

2023-11-15 05:58 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        addLog(status: currentStatus, title: currentTime, date: currentDateString)
128, 142 줄과 같은 중복 코드 제거 방법을 고민해볼 필요가 있음.

2023-11-15 05:58 UTC, JongHoon023 commented on StopWatch/StopWatch/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
왜 White Space 가 추가된 것인지?

2023-12-13 06:05 UTC, JongHoon023 approved these changes

2023-12-13 06:08 UTC, merged