[FEAT]: Start,Stop/Reset 버튼 구현 및 레이아웃 조정 , [MERGE]: feature/stopwatch-page -> main
KangJiHun1028/StopWatch pull request #8
Opened 2023-10-20 11:16 UTC by KangJiHun1028

2023-10-20 14:33 UTC, JongHoon023 requested changes

2023-10-20 14:33 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cellTypeIdentifier")
cellTypeIdentifier 상수의 값의 의미는?

2023-10-20 14:33 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cellTypeIdentifier", for: indexPath)
cellTypeIdentifier 상수의 값의 의미는?
위의 20번 줄의 값과 같은데 변하지 않는 상수 값이면 상수를 정의하여 사용할 필요가 있음

2023-10-20 14:33 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        return 7
상수 값 7을 반환할 거면 굳이 확장 함수(인지는 모르겠지만) 를 만들 필요가 있는지?

2023-10-20 14:33 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +                make.bottom.equalToSuperview() // 화면에 하단에서 부터 조정
주석은 사람마다 다르게 적긴 하는데 개인적으로 나는 아래와 같이 적음.
해당 내용은 고쳐도 되고 안 고쳐도 됨.

```.swift
make.leading.trailing.equalToSuperview()

// 화면에 하단에서 부터 조정
make.bottom.equalToSuperview()
```

2023-10-20 14:35 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cellTypeIdentifier")
Cell의 Identifier로 셀을 확인하기 위한 식별자입니다.

2023-10-20 14:36 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        return 7
셀의 개수를 임시로 반환합니다.

2023-10-20 14:36 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cellTypeIdentifier", for: indexPath)
let 상수를 정의하여 사용해보겠습니다.

2023-10-20 14:37 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +                make.bottom.equalToSuperview() // 화면에 하단에서 부터 조정
알겠습니다~

2023-10-20 14:42 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cellTypeIdentifier", for: indexPath)
어떤 방법으로 해야 좋을까요?

2023-10-20 14:49 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cellTypeIdentifier", for: indexPath)
let 으로 사용하는 것이 좋음

2023-10-20 14:50 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cellTypeIdentifier")
let 상수로 바꾸는 것을 추천

2023-10-20 14:51 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        return 7
임시라면 임시라는 의미의 함수명을 지어주는 것이 좋음.
ex) `getTempTableCellCount`

2023-10-20 15:03 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        return 7
UITableViewDataSource 프로토콜을 채택하기에 함수명을 바꿀 수 없습니다.

2023-10-20 15:03 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cellTypeIdentifier", for: indexPath)
let 을 활용하여 다시 구현하였습니다.

2023-10-21 06:03 UTC, JongHoon023 requested changes

2023-10-21 06:03 UTC, jonghoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        let hun_string = "\(hundredthSec)".count == 1 ? "0\(hundredthSec)" : "\(hundredthSec)"
상수에 underbar 사용하는 것이 Code Convension 에 맞는 것인지?

2023-10-21 06:03 UTC, jonghoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +            print("존재하지않는 태그를 가진 버튼의 입력이 들어왔습니다.")
출력문이 아닌 예외를 던지도록 변경해야 함.

2023-10-21 06:20 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +            print("존재하지않는 태그를 가진 버튼의 입력이 들어왔습니다.")
예외처리문 추가

2023-10-21 06:20 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        let hun_string = "\(hundredthSec)".count == 1 ? "0\(hundredthSec)" : "\(hundredthSec)"
상수이름 변경완료

2023-10-21 06:33 UTC, JongHoon023 requested changes

2023-10-21 06:33 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        }
try catch 를 사용하라는 의미가 아닌 예외를 던지라고 한 것임.

2023-10-21 06:43 UTC, JongHoon023 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        let hun_string = "\(hundredthSec)".count == 1 ? "0\(hundredthSec)" : "\(hundredthSec)"
<img width="713" alt="image" src="https://github.com/KangJiHun1028/StopWatch/assets/38038052/7e677d44-0933-4a82-8fb1-cc1acc23c647">

2023-10-21 06:45 UTC, KangJiHun1028 commented on StopWatch/StopWatch/Controller/StopWatchController.swift
> +        }
재수정 완료

2023-10-21 06:54 UTC, JongHoon023 approved these changes

2023-10-21 06:55 UTC, merged